name: Run Cypress Tests

on:
  push:
    branches:
      - main  # Triggers the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers the action on pull requests targeting the main branch

jobs:
  cypress:
    runs-on: ubuntu-latest  # Specifies the OS for the environment
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up Node.js environment
        with:
          node-version: '16'  # Specify your Node.js version (change if necessary)

      - name: Install dependencies
        run: |
          npm install  # Installs project dependencies

      - name: Run Cypress Tests
        run: |
          npx cypress run  # Runs the Cypress tests in headless mode
